### ISSUE TITLE
PHP 8.1.11 (phpenv) cannot find pdo_ibm.so on Ubuntu 20.04

### ISSUE THREAD

**Issue by daniilly** [php/pecl-database-pdo_ibm#14] opened 2023-01-13 13:33 UTC
**Package**: PDO_IBM-1.5.0
**Client**: IBM Data Server Driver Package V11.5.4

**1.** We installed DB2 driver package by following the IBM [instructions](https://www.ibm.com/docs/en/db2woc?topic=installing-linux-powerlinux) 
**2.** At the start of installing [PDO_ibm](https://pecl.php.net/package/PDO_IBM) with PECL. We got an issue with the "include" directory path (the folder where we have header files). We solved this problem by setting an environment **CPATH**(export CPATH=[path to "include" directory in DB2 driver package folder])
**3.** Now we got an issue with finding **pdo_ibm.so**

**Error message on step 2:**

In file included from /tmp/pecl-build/PDO_IBM/PDO_IBM-1.5.0/pdo_ibm.c:31:
/tmp/pecl-build/PDO_IBM/PDO_IBM-1.5.0/php_pdo_ibm_int.h:26:10: fatal error: sqlcli1.h: No such file or directory
   26 | #include "sqlcli1.h"
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:208: pdo_ibm.lo] Error 1

**Error message on step 3:**

/bin/bash /home/user/project/pecl-database-pdo_ibm/libtool --mode=link cc -DPHP_ATOM_INC -I/home/user/project/pecl-database-pdo_ibm/include -I/home/user/project/pecl-database-pdo_ibm/main -I/home/user/project/pecl-database-pdo_ibm -I/home/user/.phpenv/versions/8.1.11/include/php -I/home/user/.phpenv/versions/8.1.11/include/php/main -I/home/user/.phpenv/versions/8.1.11/include/php/TSRM -I/home/user/.phpenv/versions/8.1.11/include/php/Zend -I/home/user/.phpenv/versions/8.1.11/include/php/ext -I/home/user/.phpenv/versions/8.1.11/include/php/ext/date/lib -I/include  -DHAVE_CONFIG_H  -g -O2    -o pdo_ibm.la -export-dynamic -avoid-version -prefer-pic -module -rpath /home/user/project/pecl-database-pdo_ibm/modules  pdo_ibm.lo ibm_driver.lo ibm_statement.lo -Wl,-rpath, -L -ldb2
cc -shared  .libs/pdo_ibm.o .libs/ibm_driver.o .libs/ibm_statement.o  -L/home/user/project/pecl-database-pdo_ibm -ldb2  -Wl,-rpath -Wl,-soname -Wl,pdo_ibm.so -o .libs/pdo_ibm.so
/usr/bin/ld: cannot find pdo_ibm.so: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:201: pdo_ibm.la] Error 1

**Comment by NattyNarwhal** [comment] 2023-01-13 14:50
What's the command line you're running to start the build? Are you running phpize/configure directly, or are you using the `pecl`/`pear` tool? This looks like you're missing `LDFLAGS` that specify where `libdb2.so` lives, but I would think the configure step is supposed to sort that out.

**Comment by kadler** [comment] 2023-01-13 15:10
I _think_ the problem is with `-Wl,-rpath -Wl,-soname -Wl,pdo_ibm.so`. Those are gonna get passed to the linker as `ld ... -rpath -soname pdo_ibm.so`, but since no argument is specified for `-rpath`, the `-soname` argument will be interpreted as the RPATH, leaving a bare `pdo_ibm.so` which gets interpreted as a linker input. This matches with the `pdo_ibm.so: No such file or directory` error message.

Now the question is why is the `-rpath` not getting passed correctly?

**Comment by daniilly** [comment] 2023-01-16 08:52
@NattyNarwhal, thanks for the answer

At first, we tried the command `phpenv pecl PDO_IBM`. After failing with the error stated above we use directly: 

- `phpize`
- `./configure`
- `make` 

Here are the environmental constants that we set pre-driver installation:
LD_LIBRARY_PATH=/home/user/clidriver/lib
IBM_DB_HOME=/home/user/clidriver

**Comment by daniilly** [comment] 2023-01-16 09:12
@kadler, thanks for the answer

We clone the source code. 
After running `./configure` command we get the following logs:

<details> 

```
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /home/user/.phpenv/versions/8.1.11
checking for PHP includes... -I/home/user/.phpenv/versions/8.1.11/include/php -I/home/user/.phpenv/versions/8.1.11/include/php/main -I/home/user/.phpenv/versions/8.1.11/include/php/TSRM -I/home/user/.phpenv/versions/8.1.11/include/php/Zend -I/home/user/.phpenv/versions/8.1.11/include/php/ext -I/home/user/.phpenv/versions/8.1.11/include/php/ext/date/lib
checking for PHP extension directory... /home/user/.phpenv/versions/8.1.11/lib/php/extensions/no-debug-non-zts-20210902
checking for PHP installed headers prefix... /home/user/.phpenv/versions/8.1.11/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for DB2 driver for PDO... yes, shared
checking Looking for DB2 CLI libraries... checking      in yes... 
checking      in yes/lib64... 
checking      in yes/lib32... 
checking      in yes/lib... 
checking for DB2 CLI include files in default path... checking in yes... checking for PDO includes... /home/user/.phpenv/versions/8.1.11/include/php/ext
checking "/libdb400.a"... 
checking for a sed that does not truncate output... /usr/bin/sed
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged
```

</details> 

And makefile is next:

<details> 

```
srcdir = /home/user/dreamfactory/pecl-database-pdo_ibm
builddir = /home/user/dreamfactory/pecl-database-pdo_ibm
top_srcdir = /home/user/dreamfactory/pecl-database-pdo_ibm
top_builddir = /home/user/dreamfactory/pecl-database-pdo_ibm
EGREP = /usr/bin/grep -E
SED = /usr/bin/sed
CONFIGURE_COMMAND = './configure'
CONFIGURE_OPTIONS =
SHLIB_SUFFIX_NAME = so
SHLIB_DL_SUFFIX_NAME = so
AWK = nawk
shared_objects_pdo_ibm = pdo_ibm.lo ibm_driver.lo ibm_statement.lo
PHP_PECL_EXTENSION = pdo_ibm
PDO_IBM_SHARED_LIBADD = -Wl,-rpath, -L -ldb2
PHP_MODULES = $(phplibdir)/pdo_ibm.la
PHP_ZEND_EX =
all_targets = $(PHP_MODULES) $(PHP_ZEND_EX)
install_targets = install-modules install-headers
prefix = /home/user/.phpenv/versions/8.1.11
exec_prefix = $(prefix)
libdir = ${exec_prefix}/lib
prefix = /home/user/.phpenv/versions/8.1.11
phplibdir = /home/user/dreamfactory/pecl-database-pdo_ibm/modules
phpincludedir = /home/user/.phpenv/versions/8.1.11/include/php
CC = cc
CFLAGS = -g -O2
CFLAGS_CLEAN = $(CFLAGS)
CPP = cc -E
CPPFLAGS = -DHAVE_CONFIG_H
CXX =
CXXFLAGS =
CXXFLAGS_CLEAN = $(CXXFLAGS)
EXTENSION_DIR = /home/user/.phpenv/versions/8.1.11/lib/php/extensions/no-debug-non-zts-20210902
PHP_EXECUTABLE = /home/user/.phpenv/versions/8.1.11/bin/php
EXTRA_LDFLAGS =
EXTRA_LIBS =
INCLUDES = -I/home/user/.phpenv/versions/8.1.11/include/php -I/home/user/.phpenv/versions/8.1.11/include/php/main -I/home/user/.phpenv/versions/8.1.11/include/php/TSRM -I/home/user/.phpenv/versions/8.1.11/include/php/Zend -I/home/user/.phpenv/versions/8.1.11/include/php/ext -I/home/user/.phpenv/versions/8.1.11/include/php/ext/date/lib -I/include
LFLAGS =
LDFLAGS =
SHARED_LIBTOOL =
LIBTOOL = $(SHELL) $(top_builddir)/libtool
SHELL = /bin/bash
INSTALL_HEADERS =
mkinstalldirs = $(top_srcdir)/build/shtool mkdir -p
INSTALL = $(top_srcdir)/build/shtool install -c
INSTALL_DATA = $(INSTALL) -m 644

DEFS = -DPHP_ATOM_INC -I$(top_builddir)/include -I$(top_builddir)/main -I$(top_srcdir)
COMMON_FLAGS = $(DEFS) $(INCLUDES) $(EXTRA_INCLUDES) $(CPPFLAGS) $(PHP_FRAMEWORKPATH)

all: $(all_targets)
	@echo
	@echo "Build complete."
	@echo "Don't forget to run 'make test'."
	@echo

build-modules: $(PHP_MODULES) $(PHP_ZEND_EX)

build-binaries: $(PHP_BINARIES)

libphp$(PHP_MAJOR_VERSION).la: $(PHP_GLOBAL_OBJS) $(PHP_SAPI_OBJS)
	$(LIBTOOL) --mode=link $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -rpath $(phptempdir) $(EXTRA_LDFLAGS) $(LDFLAGS) $(PHP_RPATHS) $(PHP_GLOBAL_OBJS) $(PHP_SAPI_OBJS) $(EXTRA_LIBS) $(ZEND_EXTRA_LIBS) -o $@
	-@$(LIBTOOL) --silent --mode=install cp $@ $(phptempdir)/$@ >/dev/null 2>&1

libs/libphp$(PHP_MAJOR_VERSION).bundle: $(PHP_GLOBAL_OBJS) $(PHP_SAPI_OBJS)
	$(CC) $(MH_BUNDLE_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) $(EXTRA_LDFLAGS) $(PHP_GLOBAL_OBJS:.lo=.o) $(PHP_SAPI_OBJS:.lo=.o) $(PHP_FRAMEWORKS) $(EXTRA_LIBS) $(ZEND_EXTRA_LIBS) -o $@ && cp $@ libs/libphp$(PHP_MAJOR_VERSION).so

install: $(all_targets) $(install_targets)

install-sapi: $(OVERALL_TARGET)
	@echo "Installing PHP SAPI module:       $(PHP_SAPI)"
	-@$(mkinstalldirs) $(INSTALL_ROOT)$(bindir)
	-@if test ! -r $(phptempdir)/libphp$(PHP_MAJOR_VERSION).$(SHLIB_DL_SUFFIX_NAME); then \
		for i in 0.0.0 0.0 0; do \
			if test -r $(phptempdir)/libphp$(PHP_MAJOR_VERSION).$(SHLIB_DL_SUFFIX_NAME).$$i; then \
				$(LN_S) $(phptempdir)/libphp$(PHP_MAJOR_VERSION).$(SHLIB_DL_SUFFIX_NAME).$$i $(phptempdir)/libphp$(PHP_MAJOR_VERSION).$(SHLIB_DL_SUFFIX_NAME); \
				break; \
			fi; \
		done; \
	fi
	@$(INSTALL_IT)

install-binaries: build-binaries $(install_binary_targets)

install-modules: build-modules
	@test -d modules && \
	$(mkinstalldirs) $(INSTALL_ROOT)$(EXTENSION_DIR)
	@echo "Installing shared extensions:     $(INSTALL_ROOT)$(EXTENSION_DIR)/"
	@rm -f modules/*.la >/dev/null 2>&1
	@$(INSTALL) modules/* $(INSTALL_ROOT)$(EXTENSION_DIR)

install-headers:
	-@if test "$(INSTALL_HEADERS)"; then \
		for i in `echo $(INSTALL_HEADERS)`; do \
			i=`$(top_srcdir)/build/shtool path -d $$i`; \
			paths="$$paths $(INSTALL_ROOT)$(phpincludedir)/$$i"; \
		done; \
		$(mkinstalldirs) $$paths && \
		echo "Installing header files:          $(INSTALL_ROOT)$(phpincludedir)/" && \
		for i in `echo $(INSTALL_HEADERS)`; do \
			if test "$(PHP_PECL_EXTENSION)"; then \
				src=`echo $$i | $(SED) -e "s#ext/$(PHP_PECL_EXTENSION)/##g"`; \
			else \
				src=$$i; \
			fi; \
			if test -f "$(top_srcdir)/$$src"; then \
				$(INSTALL_DATA) $(top_srcdir)/$$src $(INSTALL_ROOT)$(phpincludedir)/$$i; \
			elif test -f "$(top_builddir)/$$src"; then \
				$(INSTALL_DATA) $(top_builddir)/$$src $(INSTALL_ROOT)$(phpincludedir)/$$i; \
			else \
				(cd $(top_srcdir)/$$src && $(INSTALL_DATA) *.h $(INSTALL_ROOT)$(phpincludedir)/$$i; \
				cd $(top_builddir)/$$src && $(INSTALL_DATA) *.h $(INSTALL_ROOT)$(phpincludedir)/$$i) 2>/dev/null || true; \
			fi \
		done; \
	fi

PHP_TEST_SETTINGS = -d 'open_basedir=' -d 'output_buffering=0' -d 'memory_limit=-1'
PHP_TEST_SHARED_EXTENSIONS =  ` \
	if test "x$(PHP_MODULES)" != "x"; then \
		for i in $(PHP_MODULES)""; do \
			. $$i; $(top_srcdir)/build/shtool echo -n -- " -d extension=$$dlname"; \
		done; \
	fi; \
	if test "x$(PHP_ZEND_EX)" != "x"; then \
		for i in $(PHP_ZEND_EX)""; do \
			. $$i; $(top_srcdir)/build/shtool echo -n -- " -d zend_extension=$(top_builddir)/modules/$$dlname"; \
		done; \
	fi`
PHP_DEPRECATED_DIRECTIVES_REGEX = '^(magic_quotes_(gpc|runtime|sybase)?|(zend_)?extension(_debug)?(_ts)?)[\t\ ]*='

test: all
	@if test ! -z "$(PHP_EXECUTABLE)" && test -x "$(PHP_EXECUTABLE)"; then \
		INI_FILE=`$(PHP_EXECUTABLE) -d 'display_errors=stderr' -r 'echo php_ini_loaded_file();' 2> /dev/null`; \
		if test "$$INI_FILE"; then \
			$(EGREP) -h -v $(PHP_DEPRECATED_DIRECTIVES_REGEX) "$$INI_FILE" > $(top_builddir)/tmp-php.ini; \
		else \
			echo > $(top_builddir)/tmp-php.ini; \
		fi; \
		INI_SCANNED_PATH=`$(PHP_EXECUTABLE) -d 'display_errors=stderr' -r '$$a = explode(",\n", trim(php_ini_scanned_files())); echo $$a[0];' 2> /dev/null`; \
		if test "$$INI_SCANNED_PATH"; then \
			INI_SCANNED_PATH=`$(top_srcdir)/build/shtool path -d $$INI_SCANNED_PATH`; \
			$(EGREP) -h -v $(PHP_DEPRECATED_DIRECTIVES_REGEX) "$$INI_SCANNED_PATH"/*.ini >> $(top_builddir)/tmp-php.ini; \
		fi; \
		TEST_PHP_EXECUTABLE=$(PHP_EXECUTABLE) \
		TEST_PHP_SRCDIR=$(top_srcdir) \
		CC="$(CC)" \
			$(PHP_EXECUTABLE) -n -c $(top_builddir)/tmp-php.ini $(PHP_TEST_SETTINGS) $(top_srcdir)/run-tests.php -n -c $(top_builddir)/tmp-php.ini -d extension_dir=$(top_builddir)/modules/ $(PHP_TEST_SHARED_EXTENSIONS) $(TESTS); \
		TEST_RESULT_EXIT_CODE=$$?; \
		rm $(top_builddir)/tmp-php.ini; \
		exit $$TEST_RESULT_EXIT_CODE; \
	else \
		echo "ERROR: Cannot run tests without CLI sapi."; \
	fi

clean:
	find . -name \*.gcno -o -name \*.gcda | xargs rm -f
	find . -name \*.lo -o -name \*.o | xargs rm -f
	find . -name \*.la -o -name \*.a | xargs rm -f
	find . -name \*.so | xargs rm -f
	find . -name .libs -a -type d|xargs rm -rf
	rm -f libphp$(PHP_MAJOR_VERSION).la $(SAPI_CLI_PATH) $(SAPI_CGI_PATH) $(SAPI_LITESPEED_PATH) $(SAPI_FPM_PATH) $(OVERALL_TARGET) modules/* libs/*

distclean: clean
	rm -f Makefile config.cache config.log config.status Makefile.objects Makefile.fragments libtool main/php_config.h main/internal_functions_cli.c main/internal_functions.c Zend/zend_dtrace_gen.h Zend/zend_dtrace_gen.h.bak Zend/zend_config.h
	rm -f main/build-defs.h scripts/phpize
	rm -f ext/date/lib/timelib_config.h ext/mbstring/libmbfl/config.h ext/oci8/oci8_dtrace_gen.h ext/oci8/oci8_dtrace_gen.h.bak
	rm -f scripts/man1/phpize.1 scripts/php-config scripts/man1/php-config.1 sapi/cli/php.1 sapi/cgi/php-cgi.1 sapi/phpdbg/phpdbg.1 ext/phar/phar.1 ext/phar/phar.phar.1
	rm -f sapi/fpm/php-fpm.conf sapi/fpm/init.d.php-fpm sapi/fpm/php-fpm.service sapi/fpm/php-fpm.8 sapi/fpm/status.html
	rm -f ext/iconv/php_have_bsd_iconv.h ext/iconv/php_have_glibc_iconv.h ext/iconv/php_have_ibm_iconv.h ext/iconv/php_have_iconv.h ext/iconv/php_have_libiconv.h ext/iconv/php_iconv_aliased_libiconv.h ext/iconv/php_iconv_supports_errno.h ext/iconv/php_php_iconv_h_path.h ext/iconv/php_php_iconv_impl.h
	rm -f ext/phar/phar.phar ext/phar/phar.php
	if test "$(srcdir)" != "$(builddir)"; then \
	  rm -f ext/phar/phar/phar.inc; \
	fi
	$(EGREP) define'.*include/php' $(top_srcdir)/configure | $(SED) 's/.*>//'|xargs rm -f

prof-gen:
	CCACHE_DISABLE=1 $(MAKE) PROF_FLAGS=-fprofile-generate all

prof-clean:
	find . -name \*.lo -o -name \*.o | xargs rm -f
	find . -name \*.la -o -name \*.a | xargs rm -f
	find . -name \*.so | xargs rm -f
	rm -f libphp$(PHP_MAJOR_VERSION).la $(SAPI_CLI_PATH) $(SAPI_CGI_PATH) $(SAPI_LITESPEED_PATH) $(SAPI_FPM_PATH) $(OVERALL_TARGET) modules/* libs/*

prof-use:
	CCACHE_DISABLE=1 $(MAKE) PROF_FLAGS=-fprofile-use all


.PHONY: all clean install distclean test prof-gen prof-clean prof-use
.NOEXPORT:
pdo_ibm.lo: /home/user/dreamfactory/pecl-database-pdo_ibm/pdo_ibm.c
	$(LIBTOOL) --mode=compile $(CC) -I/home/user/.phpenv/versions/8.1.11/include/php/ext -I. -I/home/user/dreamfactory/pecl-database-pdo_ibm $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/user/dreamfactory/pecl-database-pdo_ibm/pdo_ibm.c -o pdo_ibm.lo 
ibm_driver.lo: /home/user/dreamfactory/pecl-database-pdo_ibm/ibm_driver.c
	$(LIBTOOL) --mode=compile $(CC) -I/home/user/.phpenv/versions/8.1.11/include/php/ext -I. -I/home/user/dreamfactory/pecl-database-pdo_ibm $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/user/dreamfactory/pecl-database-pdo_ibm/ibm_driver.c -o ibm_driver.lo 
ibm_statement.lo: /home/user/dreamfactory/pecl-database-pdo_ibm/ibm_statement.c
	$(LIBTOOL) --mode=compile $(CC) -I/home/user/.phpenv/versions/8.1.11/include/php/ext -I. -I/home/user/dreamfactory/pecl-database-pdo_ibm $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/user/dreamfactory/pecl-database-pdo_ibm/ibm_statement.c -o ibm_statement.lo 
$(phplibdir)/pdo_ibm.la: ./pdo_ibm.la
	$(LIBTOOL) --mode=install cp ./pdo_ibm.la $(phplibdir)

./pdo_ibm.la: $(shared_objects_pdo_ibm) $(PDO_IBM_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pdo_ibm) $(PDO_IBM_SHARED_LIBADD)
```

</details> 

Can you point out the suspicious parts of the text above?

**Comment by NattyNarwhal** [comment] 2023-01-16 14:54
This is definitely broken:

```
checking for DB2 driver for PDO... yes, shared
checking Looking for DB2 CLI libraries... checking      in yes... 
checking      in yes/lib64... 
checking      in yes/lib32... 
checking      in yes/lib... 
checking for DB2 CLI include files in default path... checking in yes... checking for PDO includes... /home/user/.phpenv/versions/8.1.11/include/php/ext
checking "/libdb400.a"... 
```

The search paths don't look right. You shouldn't be seeing anything about libdb400 when using LUW.

FWIW, the way I run `./configure` is with the argument instead of the environment variable; i.e. `./configure --with-pdo-ibm=/home/calvin/opt/clidriver/`. Does that work for you as a workaround?

**Comment by daniilly** [comment] 2023-01-17 09:17
@NattyNarwhal, great thanks!

` ./configure --with-pdo-ibm=/home/user/clidriver` worked for me. Everything is being built successfully.

Here is the difference from the previous part of the `configure` log (interesting that it's still looking for libdb400):

<details>

```
checking Looking for DB2 CLI libraries... checking      in /home/user/clidriver... 
checking      in /home/user/clidriver/lib64... 
checking      in /home/user/clidriver/lib32... 
checking      in /home/user/clidriver/lib... found
checking for DB2 CLI include files in default path... checking in /home/user/clidriver... found in /home/user/clidriver
checking for PDO includes... /home/user/.phpenv/versions/8.1.11/include/php/ext
checking "/home/user/clidriver/lib//libdb400.a"... 
```
</details>

**Comment by NattyNarwhal** [comment] 2023-01-19 16:39
I'm reopening this because we should fix this. The checks seem pretty flaky.

**Closed** 2023-01-31 18:16 UTC
